version: '3.8'
services:
  mongo:
    container_name: "mongodb"
    image: mongo:6
    restart: always
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo_go_net
    restart: always
    
volumes:
  mongo_data:


networks:
  mongo_go_net:
    driver: bridge
